### ISSUE TITLE
[BUG] BD Py Edition breaks while verifying chat wrappers.

### ISSUE THREAD

**Issue by Jesseman1** [surepy/tf2_bot_detector#1]
**Describe the bug**
> BD broke while launching TF2, error reads "Failed to verify chat wrappers"

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Launch TF2BD Py Edition
> 2. Launch TF2 via launch button
> 3. Wait for launch.
> 4. See error

**Expected behavior**
> I expect the TF2BD Py Edition to load and connect.

**Logs**
> No logs.

**Screenshots**
> Error Screen:
![Bot Detector Broke](https://user-images.githubusercontent.com/26986519/218213421-b6888290-6f4a-453c-a9e8-5d1ef92188f9.jpg)

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector: 1.2.1

**Additional context**
> TF2 launch is delayed by preloading commands as part of Mastercomfig. This might be the trigger?

**Comment by surepy** [comment]
weird, I didn't touch any of the chat wrapper related code...
couple questions

1. does this happen every time?
2. what other cfgs do you run in autoexec that isn't mastercomfig?

**Comment by pizzaguylol** [comment]
Had the same issue. Getting rid of budHUD fixed it. I'm not technical enough to know why, though :<

**Comment by surepy** [comment]
does this happen with the final version of the main build of tf2bd too?

because it should behave the same, as I didn't touch chat wrapper portion
of code at all; if it behaves the same: ur only fix is choosing a different
hud for now :( sorry (I don't feel like going through chat wrappers rn asdf)

if not I have no clue.. might be a good idea to clean the customs folder ig?

**Comment by surepy** [comment]
if u accidentally launch bd twice that tends to happen

not an intended behavior but I personally don't think putting effort into
people not launching bd twice is worth it

**Comment by surepy** [comment]
going to close cuz didn't happen for a month or something

i can't outright remove chat wrapper cuz that will screw over people that don't play in english game language and stuff (and the work is kind of not worth it)
