### ISSUE TITLE
Allow hardcoded launch parameters 

### ISSUE THREAD

**Issue by Parapluie44** [surepy/tf2_bot_detector#10]
**A clear and concise description of what the problem is.**
> Some launch parameters are randomised (eg. https://github.com/surepy/tf2_bot_detector/blob/7c4b7da0d7d8dc9bf5aaf96f40a9bf386d9f85c0/tf2_bot_detector/SetupFlow/TF2CommandLinePage.cpp#L24). 

**Describe the solution you'd like**
>In order to allow the tool to cohabite with other ones that also need access to the rcon, it'd be judicious to let the user hardcode these values to whatever they choose provided they understand this is vaguely less safe.

**Comment by surepy** [comment]
sure, maybe.

for now as a workaround don't launch tf2 though bd; launch through steam but have ``-usercon +ip 0.0.0.0 +rcon_password (password) +hostport 1234`` in your launch parameters. bd will pick it up.

**Comment by surepy** [comment]
I'll make a release like maybe soontm ish for now just like pull from build artifacts or compile urself
