### ISSUE TITLE
Add "Go to > SteamHistory.net" shortcut upon right clicking a player

### ISSUE THREAD

**Issue by cl0ck-byte** [surepy/tf2_bot_detector#13]
## A clear and concise description of what the problem is
Sometimes you might want to see someone's profile history or see listed sourcebans (if you're using SH's API that is), but there's no shortcut currently in Bot Whacker.

## Describe the solution you'd like
Add SteamHistory.net to shortcuts.

## Additional context
None.

**Comment by surepy** [comment]
technically u can do it urself now by editing settings.json
