### ISSUE TITLE
Add "reason" to the mark user UI

### ISSUE THREAD

**Issue by MissPotato** [surepy/tf2_bot_detector#14]
**A clear and concise description of what the problem is.**
> I currently have a pretty sizable list as I've added a lot of bots.  It is a bit awkward to manually add the reason to each account in the json. 

**Describe the solution you'd like**
> Would be nice if, when I mark a player, I could provide my reason for marking the player. That way I don't have to manually add it to the json for each account. 

**Describe alternatives you've considered**
> Perhaps instead of prompting the user for each mark it is just a separate entry in the right click menu? That way people who don't care to provide a reason, can just do what they've always done with no change.

**Additional context**
> It would also help for the "racist" option as the auto-flag only takes in account chat messages. If I flag someone as racist I could easily make the reason "Said slur over mic."  (Maybe also change "racist" to bigot, though I fear that might break old lists?)

**Comment by surepy** [comment]
![image](https://github.com/surepy/tf2_bot_detector/assets/24486494/05bee991-0828-4a88-8ff4-3044e64d0504)

but it's right there

**Comment by MissPotato** [comment]
I am so blind lmao, sorry
