### ISSUE TITLE
[BUG] Build #76 entry point not found

### ISSUE THREAD

**Issue by MissPotato** [surepy/tf2_bot_detector#15]
**Describe the bug**
Attempting to run build 76 returns an error about entry point not found
https://i.imgur.com/8RtoJcR.png

**To Reproduce**
1) Download https://github.com/surepy/tf2_bot_detector/suites/15174852706/artifacts/867103944
2) Extract to folder
3) Get entry point error

**Expected behavior**
> Program to boot

**Logs**
> Fails to even boot

**Screenshots**
> SS of error https://i.imgur.com/Is5szkA.png
SS of folder https://i.imgur.com/8RtoJcR.png

**Desktop (please complete the following information):**
> - OS: Windows 10,
> - Version of bot detector 1.5.7.76

**Additional context**
> Add any other context about the problem here.

**Comment by surepy** [comment]
ur downloading the wrong file 
https://github.com/surepy/tf2_bot_detector/suites/15174852706/artifacts/867103940

**Comment by MissPotato** [comment]
Same issue, I just linked the wrong thing.

**Comment by surepy** [comment]
fixed in f92230a982e9f5c5c9ed63dd8160f0d6e98b18a3, artifact builds should work out of the box.
