### ISSUE TITLE
Add date/UNIX timestamp at which player was marked

### ISSUE THREAD

**Issue by cl0ck-byte** [surepy/tf2_bot_detector#16]
## A clear and concise description of what the problem is.
Sometimes you might want to see at what date specific player was marked (automatically or manually) and there is currently no timestamp for such action.

## Describe the solution you'd like
Add date/epoch/unix timestamp at which player was marked. Visible upon player inspection.

## Additional context
To avoid breaking old lists, do not require date.

**Comment by surepy** [comment]
u mean like on the context menu?

fyi its already there in a lot of the playerlist if u look at the json

**Comment by cl0ck-byte** [comment]
> u mean like on the context menu?

yeah on context menu if you hover over a mouse

> fyi its already there in a lot of the playerlist if u look at the json

cool

**Comment by surepy** [comment]
![image](https://github.com/surepy/tf2_bot_detector/assets/24486494/99b605bb-73b2-420b-88ef-571c6d667baa)
smth like that
