### ISSUE TITLE
Stop spamming about invisible friends list

### ISSUE THREAD

**Issue by cl0ck-byte** [surepy/tf2_bot_detector#17]
## A clear and concise description of what the problem is.
`[19:18:26] WorldState.cpp(119):UpdateFriends: Failed to access our friends list (our friends list is private/friends only, and the Steam API is bugged). The tool will not be able to show who is friends with you.` every god damn second

### Describe the solution you'd like
Just check it every hour or less/more

### Additional context
500mb log files, yikes

**Comment by surepy** [comment]
incredible
