### ISSUE TITLE
[BUG] Github menu points to old github

### ISSUE THREAD

**Issue by luckydonald** [surepy/tf2_bot_detector#18]
**Describe the bug**
![image](https://github.com/surepy/tf2_bot_detector/assets/2737108/62df4620-d348-4f54-86e3-a5f6a90d311e)

**To Reproduce**
> 1. Open app
> 2. Click "Help"
> 3. Click "Open Github"
> 4. The wrong repo opens.

**Expected behavior**
> This repo opens.

Because there's no direct link to this repo, currently I always have to use [**fork.rip**/PazerOP/tf2_bot_detector](https://fork.rip/PazerOP/tf2_bot_detector) to find this again.

**Logs**
> `No.spy-voiceline.wav`

**Screenshots**
> See above.

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector 1.5.10.0

**Additional context**
> Add any other context about the problem here.

**Comment by surepy** [comment]
that's a menu that exists

**Comment by luckydonald** [comment]
Thanks!

**Comment by surepy** [comment]
I'll update it as a release binary in like a bit
