### ISSUE TITLE
Check player's friends list for matches on playerlists

### ISSUE THREAD

**Issue by name71** [surepy/tf2_bot_detector#2]
When determining if someone is cheating, it's useful to check their friends list for other known cheaters. Adding something that automatically checks their friendslist for matches on your playerlists would be useful - it would say something like "Friends with 10 users marked as cheater on playerlist.json (50%)" with 50% being the % of friends who are cheaters. It might be better to check both ways (checking the player you are hovering's friends list as well as checking those marked in your playerlist for their id, in case they have private friends) but I'm unsure if that would be too complicated or spam requests too much if you have a large list or something.

**Comment by surepy** [comment]
it should be trivial... in theory, I'll investigate later.

**Comment by surepy** [comment]
hi, does this look fine? 

![image](https://github.com/surepy/tf2_bot_detector/assets/24486494/5c7a05b5-11b3-41d8-9413-5e1c565f45c4)
