### ISSUE TITLE
[BUG] TF2 updated and changed the executable

### ISSUE THREAD

**Issue by birchish** [surepy/tf2_bot_detector#29]
**Describe the bug**
> Team Fortress 2 updated and has changed the executable's name to **tf.exe** and **tf_win64.exe**. This prevents tf2bd from detecting the executable as it was named **hl2.exe** before.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Launch tf2bd
> 2. Launch Team Fortress 2
> 3. It does not detect the game.

**Expected behavior**
> Tf2bd to detect Team Fortress 2.

**Screenshots**
> ![image](https://github.com/surepy/tf2_bot_detector/assets/77995100/12ab3fa2-a224-4a8d-8ac6-c36f4a5559fe)

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector 1.5.14

**Comment by surepy** [comment]
fixed in 1.6, check releases.
