### ISSUE TITLE
[BUG] We're still sending requests to pazer's proxy service 

### ISSUE THREAD

**Issue by AlexioShow** [surepy/tf2_bot_detector#3]
Whenever you're opening the app : `WorldState.cpp(324):UpdateFriends: Failed to update our friends list: class tf2_bot_detector::http_error: Failed to HTTP GET https://tf2bd-util.pazer.us:443/SteamAPIProxy/ISteamUser/GetFriendList/v0001?steamid=76561198190865246: <UNKNOWN>(HTTP 523)`

And then it keep spamming : `SteamAPI.cpp(337):GetTF2PlaytimeAsync: class std::exception: SteamAPI.cpp(337):GetTF2PlaytimeAsync: : There was an HTTP error encountered when getting the result.`

And lastly : `BatchedAction.h(78):Update: Failed to get batched action future: class std::exception: Failed to HTTP GET https://tf2bd-util.pazer.us:443/SteamAPIProxy/ISteamUser/GetPlayerSummaries/v0002?steamids=`[insert multiples steam IDs here]

![image](https://github.com/surepy/tf2_bot_detector/assets/103590506/c6ea701f-e950-4ab1-9279-e9a8801c0434)

![image](https://github.com/surepy/tf2_bot_detector/assets/103590506/d1fc0c50-1090-4988-aa13-e8338a96e8ba)

How do i fix it?

**Comment by AlexioShow** [comment]
I'm using the lastest version : v.1.5.2.0 (sleepybuild)

**Comment by Caketaco** [comment]
Problem has not fixed itself for me, having the same issue,

**Comment by Caketaco** [comment]
Spoke too soon, fixed by using direct steam api mode as opposed to proxied.

**Comment by surepy** [comment]
I'm gonna reopen so I remind myself to actually disable that

**Comment by surepy** [comment]
okay, proxied mode is gone now and there's is a nice setup menu at the start
![first time setup](https://github.com/surepy/tf2_bot_detector/assets/24486494/38bab41a-24af-4f82-af45-968236e04adc)

if upgrading set it from settings
![settings](https://github.com/surepy/tf2_bot_detector/assets/24486494/ab390f8a-c1f3-46a1-824e-b13b2b1f2682)
