### ISSUE TITLE
Feature to automatically close TF2BD upon TF2 closing

### ISSUE THREAD

**Issue by S1rMaxim** [surepy/tf2_bot_detector#30]
**A clear and concise description of what the problem is.**
> It's be nice to have TF2BD close whenever you exit TF2 as well so you don't have to do it manually each time. Sometimes I forget to close TF2BD after closing TF2 and it causes Steam and Discord Rich Presence to still say I'm playing TF2.

**Describe the solution you'd like**
> Create a feature (as an optional setting) that closes TF2BD upon detecting the game also being closed after having been launched with the tool.

**Additional Information**
> Might be helpful to avoid closing TF2BD upon a game crash and not a manual exit? Though I understand if that's simply not possible because there isn't a way to distinguish; I don't mind if the tool closes even upon a crash, it'd be a very nice QOL improvement either way.

**Comment by surepy** [comment]
> Might be helpful to avoid closing TF2BD upon a game crash and not a manual exit?

It's not _impossible_, but I just can't be arsed to implement that lol.

like i have to listen to the exit code of tf2 exe and i have to code that for both platforms and yada yada... 

For my time and sanity (and less complexity) sake, I've decided that I'll just make the user to just re-launch the application on that, sorry.

anyway, next release. whenever that is.

![image](https://github.com/surepy/tf2_bot_detector/assets/24486494/d739a622-4aff-49d7-a25e-854662c73d76)
