### ISSUE TITLE
[BUG] Launching the game via TF2BD causes vsync issues

### ISSUE THREAD

**Issue by Hedwig7s** [surepy/tf2_bot_detector#35]
**Describe the bug**
When launcing tf2 via TF2BD, there's screen tearing

**To Reproduce**
1. Launch TF2BD
2. Launch TF2 via TF2BD
3. Click the "Find a Game" button
4. It'll be warped while opening (applies ingame too)

**Expected behavior**
No screen tearing (launching via steam has no issues)

**Desktop (please complete the following information):**
Linux Mint 21.3

**Additional context**
Recording TF2 with something like OBS does not capture the screen tearing

**Comment by surepy** [comment]
What was the issue for this?

**Comment by Hedwig7s** [comment]
I made it originally because launching via steam didn't cause the issue but then it started happening there too

**Comment by Hedwig7s** [comment]
Lag from TF2BD or the terminal that ran the launch script does affect TF2 though
