### ISSUE TITLE
[BUG] 1.6.4 crashes on startup

### ISSUE THREAD

**Issue by Icharaimes** [surepy/tf2_bot_detector#42]
**Describe the bug**
> When trying to open the latest version, it crashes before launching.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Attempt to open "tf2_bot_detector.exe"
> 2. Instead of the program opening, a crash log is created.

**Expected behavior**
> The program to open.

**Logs**
> I can't open the program to get logs, but here is the crash report file: 
[tfbd_crash_2024-08-24-10-31-17.zip](https://github.com/user-attachments/files/16736971/tfbd_crash_2024-08-24-10-31-17.zip)

**Desktop (please complete the following information):**
> - OS: Windows 11
> - Version of bot detector: 1.6.4.210

**Additional context**
> Previous version (1.6.3.196) launched without issue and continues to do so. Triple checked to make sure I downloaded the Windows version and not the Linux version. No files were added/modified from the downloaded zip file.

**Comment by surepy** [comment]
bruh, will investigate; use prev version for now.

**Comment by surepy** [comment]
now this is interesting 

![stack](https://github.com/user-attachments/assets/436ed74f-e16d-4fb9-96d4-3c06ce3b536c)

my guess is it's either self-destructing under SetThreadUILanguage or CoInitializeEx because that's the only time runprogram will create a new thread

does this happen even after a reboot? because this is super weird and doesn't happen on machines i have access to (+1)

**Comment by Icharaimes** [comment]
Tested again and can confirm the issue persists after a reboot.

**Comment by surepy** [comment]
can you try launching the latest _debug_ artifact thanks

**Comment by Icharaimes** [comment]
Tried the "windows_latest_x64" and "windows_latest_x86" debug artifacts and got several error popups saying "The code execution cannot proceed because MSVCP140D.dll was not found. Reinstalling the program may fix this problem" along with a similar popup for VCRUNTIME140D.dll, VCRUNTIME140_1D.dll, and ucrtbased.dll. Think I tried the right artifact but not certain. Tried again after a reinstall of the MS Visual C++ redistributable and got the same errors.

**Comment by surepy** [comment]
ngl i forgot that people just dont have those installed

how about the release build does that crash still

**Comment by Icharaimes** [comment]
The 1.6.4.212 release artifact produces this: 
[tfbd_crash_2024-08-26-20-53-17.zip](https://github.com/user-attachments/files/16755072/tfbd_crash_2024-08-26-20-53-17.zip)

Not sure if the issue is the same or if it crashes for a different reason but I suspect the former because it still crashes before launching.

**Comment by surepy** [comment]
I don't know how this doesn't create a crash on my compiler and previous versions of msvc but it is what it is I guess

I'm guessing this probably should have fixed the crash

**Comment by Icharaimes** [comment]
Still getting the same issues for the debug (error messages) and release ([tfbd_crash_2024-08-28-14-16-09.zip](https://github.com/user-attachments/files/16787462/tfbd_crash_2024-08-28-14-16-09.zip)) artifacts for 1.6.4.213 unfortunately.

**Comment by surepy** [comment]
If this dont work ill have to do more digging i guess

sorry for making u run this over and over again, this doesnt happen on literally any of the hardware i have + my friend's hardware

**Comment by Icharaimes** [comment]
Didn't seem to work ([tfbd_crash_2024-08-29-20-15-01.zip](https://github.com/user-attachments/files/16808578/tfbd_crash_2024-08-29-20-15-01.zip)).

No worries as far as me testing out each new artifact until it gets resolved though. More than happy to do what I can to try to get this issue fixed.

**Comment by surepy** [comment]
https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660
https://stackoverflow.com/questions/44998460/c-stdmutex-lock-access-violation-in-visual-studio-2017

looks like microsoft is out here breaking my shit 

if this stupid version doesn't work try just updating vcredist

https://aka.ms/vs/17/release/vc_redist.x64.exe

```That is, if you’re seeing crashes due to null dereferences in mutex locking machinery, you’re deploying a program built with new STL headers, but without a sufficiently new msvcp140.dll, which is unsupported. You need to be (re)distributing a new STL DLL too. (This is what’s causing the “not all users see this” behavior```

**Comment by Icharaimes** [comment]
The good news is that between this update and updating vcredist, it doesn't crash the same way anymore. The bad news is that it now crashes in a different way, producing a "Fatal Error" message that displays the following:

Filesystem:EnsureInit failed

Error source filename: D:\a\tf2_bot_detector\tf2_bot_detector\Filesystem.cpp:228
Error source function: class std::filesystem::path __cdecl `anonymous-namespace'::Filesystem::GetLocalAppDataDir(void) const

I don't know what that directory is as that isn't a directory that exists on my machine's D: drive.

**Comment by Icharaimes** [comment]
Alright so while the above is true for the 1.6.4.215 release artifact (the debug still had the dll messages), the 1.6.4.210 release version now works for me after updating vcredist to the linked version. Shoutout to Microsoft for constantly changing things that don't need to be changed. Many thanks for working me through this.

**Comment by surepy** [comment]
> Alright so while the above is true for the 1.6.4.215 release artifact (the debug still had the dll messages), the 1.6.4.210 release version now works for me after updating vcredist to the linked version. Shoutout to Microsoft for constantly changing things that don't need to be changed. Many thanks for working me through this.

yea i just fucked up and apparently logs can't be init before filesystem, reverted it just now.

you're welcome lol enjoy game
