### ISSUE TITLE
[BUG] High CPU usage when the app is open

### ISSUE THREAD

**Issue by kamild1996** [surepy/tf2_bot_detector#44]
**Describe the bug**
When the application is open, its CPU usage hovers at around 15% - while it doesn't sound like much, it's enough to cause severe in-game stutters when my game's framerate goes below the FPS cap. Closing TF2BD solves the stuttering issue entirely. What I've tried:
- Enable "Sleep when unfocused"
- Restore the default UI scale
- Reduce the target frame time for TF2BD to the highest value (the CPU usage does not change regardless of the value)
- Minimizing the app when not in active use (the CPU usage does not change at all)
- Restore the following Nvidia settings that are applied system-wide to their defaults: vertical sync (let 3D application decide), max framerate (off), max background framerate (off), low latency mode (off)
- Disabling my antivirus software

**To Reproduce**
Simply open the app. Even without TF2 open, the CPU usage is already present, and seems to slightly increase even more when the game is open and TF2BD connects to it.

**Expected behavior**
The CPU usage of the app is much smaller.

**Logs**
[debug_report.zip](https://github.com/user-attachments/files/17646720/debug_report.zip)

**Screenshots**
![image](https://github.com/user-attachments/assets/4140ba12-3130-41b5-9e0b-8c5bb03d4f46)
![image](https://github.com/user-attachments/assets/0e9d1b2a-98d4-489f-bbf5-ab98100624db)

**Desktop (please complete the following information):**
- OS: Windows 11 23H2
- Version of bot detector: 1.6.4.210

**Additional context**
Unfortunately I'm not sure whether or not this problem is new or not. I've never noticed the app's CPU usage when playing on a 144 Hz monitor, but after upgrading to a 280 Hz one and seeing my stuttering issues when my FPS goes as far as a few frames below that cap, I started seeking answers, and closing TF2BD turned out to be the answer.

**Comment by surepy** [comment]
interesting, might have to look into the profiler again...   

do you know what ur cpu usage was when it was the 144hz monitor or was it the same   

realistically it should be like this:  
![image](https://github.com/user-attachments/assets/103b85b1-8742-47a3-9128-8643d7c8f34f)

p.s.   
``Disabling my antivirus software ``
wtf don't do that ever

**Comment by kamild1996** [comment]
> do you know what ur cpu usage was when it was the 144hz monitor or was it the same

Unfortunately I have no clue, I never checked the app's CPU usage before since I never really had performance issues before. But if I set my current monitor to 144 Hz, the CPU usage remains the same, so I'd wager I have had this problem for an unknown amount of time, it just never had a chance to bother me.

> p.s. `Disabling my antivirus software ` wtf don't do that ever

I know, it's just a troubleshooting step - especially since I don't use Defender like most people do.

**Comment by kamild1996** [comment]
I tried to look deeper into this. I opened Process Hacker and looked around, found this information on the list of threads - nvoglv64.dll!DrvValidateVersion+0xdee0 is responsible for most of the CPU usage:
![image](https://github.com/user-attachments/assets/894b2dd4-39f0-440f-b888-0d1abc3bfb6e)
Unfortunately, I couldn't find a lot of information about this problem other than this thread on Nvidia's forums: https://forums.developer.nvidia.com/t/mysterious-cpu-usage-issue/53710/6
The OP reported an issue that sounds familiar - about 12% of CPU usage on a 64-bit OpenGL program caused by the aforementioned thread. But their other findings didn't match - minimizing the app or disabling all monitors other than my primary does not fix the problem, even after restarting the app. A moderator suggested that this problem happens when the app "enters the full-screen exclusive flipping mode on the rendering display", which I don't think applies to TF2BD, but it did remind me of a Windows 11's "optimisations for windowed games" feature that seems to be messing with presentation models. Disabling that feature also didn't do anything, and neither did playing with the "Vulkan/OpenGL present method" option in Nvidia's control panel. 

I have also went ahead and tried older releases of TF2BD - **seems like some change from 1.5.13 is causing trouble**.
- 1.6.3 to 1.6.4: problem as described on both versions
- 1.6.0 to 1.6.2: the CPU usage is noticeably less (7-8%) but according to ProcessHacker, it's no longer caused by nvoglv64.dll, but by the TF2BD's process itself
- 1.5.13 to 1.5.14: suddenly exhibits the same problem 1.6.3 and 1.6.4 has, the CPU usage is back up and it's caused by nvoglv64.dll again.
- 1.5.12: the problem is gone, CPU usage is down to 0-0.2%
- Pazer's latest release (1.2.1): both 32-bit and 64-bit versions also do not exhibit this problem

**Comment by surepy** [comment]
This... is really weird thats for sure.

My ability to research this might help limited due to me having an AMD gpu so literally never having this issue, but I'll try to look into it (eventually... currently doing other stuff in my life)

**Comment by kamild1996** [comment]
Nvidia just released a new driver, and one of the fixes include:
`[Bluestacks/Corsair iCUE] May display higher than normal CPU usage [4895184][4893446]`

I figured I can try updating and seeing if it happens to affect TF2BD, and... here you go lol
![image](https://github.com/user-attachments/assets/13a6513a-5416-4e25-aece-ca6afa1319a9)

Fixed by updating the Nvidia driver to 566.14 released on November 12th 2024 :)

**Comment by surepy** [comment]
> Nvidia just released a new driver, and one of the fixes include:
> 
> `[Bluestacks/Corsair iCUE] May display higher than normal CPU usage [4895184][4893446]`
> 
> 
> 
> I figured I can try updating and seeing if it happens to affect TF2BD, and... here you go lol
> 
> ![image](https://github.com/user-attachments/assets/13a6513a-5416-4e25-aece-ca6afa1319a9)
> 
> 
> 
> Fixed by updating the Nvidia driver to 566.14 released on November 12th 2024 :)

Oh, thanks nvidia (lol)

I've done some of my own limited research and read that swapinterval=1 yields high cpu usage in nvidia gpus and was about to make a build doing that tonight but i guess i dont have to anymore lol

(Ref: https://github.com/mpv-player/mpv/issues/152)

Glad that was resolved pretty easily
