### ISSUE TITLE
[BUG] Using some huds will crash the game itself

### ISSUE THREAD

**Issue by surepy** [surepy/tf2_bot_detector#5]
why

**Describe the bug**
Using huds with chat resources will crash the game itself.

**To Reproduce**
![image](https://github.com/surepy/tf2_bot_detector/assets/24486494/9fca04d5-8084-4bba-ad15-9cd4b8e8b501)

**Expected behavior**
Not crash?

**Logs**
Not Applicable

**Desktop:**
- OS: Windows 
- Version of bot detector: All Versions (including future versions)

**Additional context** 
This also happens in normal tf2bd, its a TF2 issue. (thank u valve)

**Potential Fixes (ideas)** 
- ~~remove chat wrappers~~ 
I won't be doing this as it will screw over people not having their game language set to English
- make chat wrapper a constant and make user merge resources
potential new abuse angle?
- make it automatically merge with existing chat wrapper resources
wow that sounds like a can of worms I kind of don't want to do that
- cry 
(and tell the users about this reason)
current option at the moment

might have a resource detection thing or something idk ugh

**Comment by uhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
sorry i described it poorly, by 'it' I meant tf2 bot detector just auto closes, not the game itself. it says "generating chat wrappers 19%" then closes.

**Comment by surepy** [comment]
> sorry i described it poorly, by 'it' I meant tf2 bot detector just auto closes, not the game itself. it says "generating chat wrappers 19%" then closes.
> 

wtf that's a completely new issue lol

make a new issue with logs

**Comment by surepy** [comment]
oh, im just bad at reading, will track this at #6 anyway
