### ISSUE TITLE
[BUG] Using some huds will stop TF2BD from starting

### ISSUE THREAD

**Issue by name71** [surepy/tf2_bot_detector#6]
**Describe the bug**
> Using huds with chat resources and then opening TF2BD will stop loading at 19% "generating chat message wrappers" and then it will close automatically

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Use a hud with that contains the files chat_english, chat_russian etc in resource folder e.g. budhud
> 2. Open TF2BD
> 3. It will pause on 19% and then close

**Expected behavior**
> Should load to 100% then allow you to start the game

**Logs**
> Log file contains nothing at all 
[console_2023-05-29_22-56-11.log](https://github.com/surepy/tf2_bot_detector/files/11594309/console_2023-05-29_22-56-11.log)

**Screenshots**
> 

https://github.com/surepy/tf2_bot_detector/assets/86732631/a916c7d5-e9d8-408b-ace8-5d35e036b60b

**Desktop (please complete the following information):**
> - OS: Windows 11
> - Version of bot detector v1.5.3.0 (sleepybuild) but also happens on latest normal TF2BD

**Additional context**
> You can remove those text files to allow it to launch, but that breaks the hud

**Comment by surepy** [comment]
I'll reproduce this later and try to fix, my list of "ideas for fix" loosely applies still.

**Comment by surepy** [comment]
I've used budhud for a couple hours now; and i can't seem to reproduce it, if there is, can you send a crash mdmp file?
