### ISSUE TITLE
[BUG] Team assignment broken on VSH maps

### ISSUE THREAD

**Issue by kamild1996** [surepy/tf2_bot_detector#8]
**Describe the bug**
> While playing on VSH maps (tested on official Valve servers), TF2BD has trouble properly recognizing player teams - instead of showing everyone except current Hale as "Friendly", it shows half of the players as "Friendly" and "Enemy", as if I was playing on a normal server. This prevents features such as auto-kick from working reliably.

**To Reproduce**
> 1. Join a Valve server hosting a VSH map (Nucleus/Distillery/Skirmish/Tiny Rock)
> 2. Look at the team assignment in TF2BD.

**Logs**
[2023-08-04_15-40-14.log](https://github.com/surepy/tf2_bot_detector/files/12261388/2023-08-04_15-40-14.log)

**Desktop:**
> - OS: Windows 11
> - Version of bot detector: v1.5.7

**Comment by surepy** [comment]
I'll look into it.

**Comment by surepy** [comment]
![tf_lobby_debug returning wrong data](https://github.com/surepy/tf2_bot_detector/assets/24486494/1496fea6-a47c-403a-a0b6-b84b753a6f6d)

valve, please

I can make it so that it tries to vote everyone i guess but this is.. lol

**Comment by luckydonald** [comment]
Can the tool detect the map name?
In that case, an option to do that on vsh maps would be an idea.

Or simply a "Ignore Teams" toggle next to the chat spam toggles would be also working.
If it's gonna be manually pressing one button, that's still better than having to votekick yourself.

**Comment by surepy** [comment]
> Can the tool detect the map name? In that case, an option to do that on vsh maps would be an idea.
> 
> Or simply a "Ignore Teams" toggle next to the chat spam toggles would be also working. If it's gonna be manually pressing one button, that's still better than having to votekick yourself.

![votekick-ignores-team-state](https://github.com/surepy/tf2_bot_detector/assets/24486494/0fbea2cb-e46d-4026-8ad4-c665414a6f91)

~~not really tested code, you can test for yourself in the latest build artifacts.~~  released 
enabling this option will make auto kick cycle through every cheater in the entire server in only ``ze_`` (zombie escape) and ``vsh_`` maps (hopefully)  
reopen or make a new issue if issues arise, or need a new map prefix added.  

I'll make it a release in.... when I feel like it lmfao
